-- 코드를 입력하세요

# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES AS FAVORITES
# FROM REST_INFO R NATURAL JOIN 
#     (SELECT RANK PARTITION BY FAVORITES AS FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE) F
# WHERE R.FAVORITES = F.FAVORITES AND R.FOOD_TYPE = F.FOOD_TYPE
# ORDER BY FOOD_TYPE DESC;

SELECT F.FOOD_TYPE, F.REST_ID, F.REST_NAME, FAVORITES
FROM (
SELECT FOOD_TYPE, REST_ID, REST_NAME,FAVORITES, RANK() OVER (
    PARTITION BY FOOD_TYPE 
    ORDER BY FAVORITES DESC
    )AS RNK
    FROM REST_INFO
    ) F
WHERE RNK = 1
ORDER BY FOOD_TYPE DESC;
