-- 코드를 작성해주세요
SELECT ID, CASE 
WHEN NUMBER <= CNT*0.25 THEN 'CRITICAL'
WHEN NUMBER > CNT*0.25 AND NUMBER <= CNT*0.50 THEN 'HIGH'
WHEN NUMBER > CNT*0.50 AND NUMBER <= CNT*0.75 THEN 'MEDIUM'
WHEN NUMBER > CNT*0.75 THEN 'LOW'
END AS COLONY_NAME

FROM (
   SELECT ID, PARENT_ID, SIZE_OF_COLONY, DIFFERENTIATION_DATE, GENOTYPE, 
    ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS NUMBER,
    COUNT(*) OVER () AS CNT
    FROM ECOLI_DATA
    ) F
    ORDER BY ID ASC;
