-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, 
COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE O LEFT JOIN USER_INFO U ON O.USER_ID = U.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER is not null
ORDER BY YEAR(SALES_DATE) ASC , MONTH(SALES_DATE) ASC, GENDER ASC;