-- 코드를 입력하세요

SELECT CONCAT('/home/grep/src/',U.BOARD_ID,'/',U.FILE_ID,U.FILE_NAME,FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE U
NATURAL JOIN (SELECT BOARD_ID, VIEWS AS TMP
    FROM USED_GOODS_BOARD
    GROUP BY BOARD_ID
    ORDER BY VIEWS DESC
    LIMIT 1 ) B
ORDER BY U.FILE_ID DESC;