-- 코드를 입력하세요
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRODUCT_NAME, PRICE, RANK() OVER 
    (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RNK
    FROM FOOD_PRODUCT
) F
WHERE RNK = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC;